name: Generate-ASCII Artwork Multijob

on: push

jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
        
        - name: Install Cowsay Program
          run: sudo apt-get install cowsay -y

        - name: Execute artwork
          run: cowsay -f dragon "Run for cover, Iam a dragon.... RAWR" >> dragon.txt 
        
        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v4.3.5
          with:
            name: dragon.txt
            path: dragon.txt

    
    test_job:
        needs: build_job
        runs-on: ubuntu-latest
        steps:   
        - name: Download a Build Artifact
          uses: actions/download-artifact@v4.1.8
          with:
             name: dragon.txt

        - name: Sleep for 30 seconds
          run: sleep 10
        
        - name: Tests whether image exisits
          run: grep -i "dragon" dragon.txt 

    deploy_job:
        needs: [build_job, test_job]
        runs-on: ubuntu-latest
        steps:
        - name: Download a Build Artifact
          uses: actions/download-artifact@v4.1.8
          with:
               name: dragon.txt
        - name: Read File
          run: cat dragon.txt

